### ISSUE TITLE
Commits are not linked to your Github profile

### ISSUE THREAD

**Issue by olegberman** [Hermanya/animatio#1]
<img width="316" alt="screen shot 2015-07-03 at 2 12 12 pm" src="https://cloud.githubusercontent.com/assets/6267340/8503460/891fbf70-218d-11e5-8d1e-a40e04791b57.png">

This data is from `git config` and your email is not linked to your username, refer to https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user

**Comment by Hermanya** [comment]
:+1:
